# Generated by Django 4.1.13 on 2024-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_product_store_price_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="value",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.ManyToManyField(to="app.price"),
        ),
    ]
