# Generated by Django 4.1.13 on 2024-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_price_value_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
