# Generated by Django 4.1.13 on 2024-01-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_price_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="app.price"
            ),
            preserve_default=False,
        ),
    ]
