# Generated by Django 4.1.13 on 2024-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_producthistory_product_description_product_store_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producthistory",
            options={
                "verbose_name": "Price history",
                "verbose_name_plural": "Price history",
            },
        ),
        migrations.AddField(
            model_name="producthistory",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
