# Generated by Django 4.1.13 on 2024-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_producthistory_options_producthistory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
