# Generated by Django 4.1.13 on 2024-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
